name: Deploy to SERVER via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on SERVER via SSH (git pull + deploy)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/galerie
            git pull origin main
            chmod +x ./deploy.sh
            ./deploy.sh

# Configuration requise :
# - Définir les secrets GitHub suivants dans le repo :
#   - SERVER_HOST : IP ou nom de domaine du SERVER
#   - SERVER_USER : utilisateur SSH
#   - SERVER_SSH_KEY : clé privée SSH (format PEM, sans passphrase)
#   - SERVER_PORT : port SSH (22 par défaut)
# - Le repo doit être cloné dans /var/www sur le SERVER et avoir les droits d'accès SSH.